/res
  /layout
    activity_login.xml
    activity_registration.xml
    activity_bakery_list.xml
    activity_product_list.xml
    activity_reservation.xml
    activity_reservation_history.xml
/src
  /java
    /com/example/bakeryreservation
      model
        Bakery.java
        Product.java
        Reservation.java
      adapter
        BakeryListAdapter.java
        ProductListAdapter.java
        ReservationHistoryAdapter.java
      util
        DateTimeUtils.java
      activity
        LoginActivity.java
        RegistrationActivity.java
        BakeryListActivity.java
        ProductListActivity.java
        ReservationActivity.java
        ReservationHistoryActivity.java
